// pattern: Imperative Shell
//
// auth.md agent-registration queries. Reads and writes the `agent_identities` and
// `agent_claim_attempts` tables (V037); returns plain data structs. No JWT validation,
// code generation, or route-level state-machine decisions live here.

#![allow(dead_code)]

use common::{ApiError, ErrorCode};
use sqlx::Sqlite;

use super::is_unique_violation;

type IdentitySqlRow = (
    String,
    Option<String>,
    String,
    Option<String>,
    Option<String>,
    Option<String>,
    String,
    Option<String>,
    String,
    Option<String>,
    Option<String>,
    Option<String>,
    String,
    String,
    String,
);

type ClaimAttemptSqlRow = (
    String,
    String,
    String,
    String,
    Option<String>,
    String,
    String,
    bool,
);

/// Registration method recorded for an auth.md agent identity.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum RegistrationType {
    IdentityAssertion,
    ServiceAuth,
    Anonymous,
}

impl RegistrationType {
    pub(crate) fn as_str(self) -> &'static str {
        match self {
            RegistrationType::IdentityAssertion => "identity_assertion",
            RegistrationType::ServiceAuth => "service_auth",
            RegistrationType::Anonymous => "anonymous",
        }
    }

    fn from_string(value: String) -> Self {
        match value.as_str() {
            "identity_assertion" => RegistrationType::IdentityAssertion,
            "service_auth" => RegistrationType::ServiceAuth,
            "anonymous" => RegistrationType::Anonymous,
            _ => RegistrationType::Anonymous,
        }
    }
}

/// Durable lifecycle status for an agent identity.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum AgentIdentityStatus {
    Active,
    Claimed,
    Revoked,
}

impl AgentIdentityStatus {
    pub(crate) fn as_str(self) -> &'static str {
        match self {
            AgentIdentityStatus::Active => "active",
            AgentIdentityStatus::Claimed => "claimed",
            AgentIdentityStatus::Revoked => "revoked",
        }
    }

    fn from_string(value: String) -> Self {
        match value.as_str() {
            "active" => AgentIdentityStatus::Active,
            "claimed" => AgentIdentityStatus::Claimed,
            "revoked" => AgentIdentityStatus::Revoked,
            _ => AgentIdentityStatus::Revoked,
        }
    }
}

/// Durable lifecycle status for a user-code claim ceremony attempt.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum ClaimAttemptStatus {
    Pending,
    Completed,
    Expired,
}

impl ClaimAttemptStatus {
    pub(crate) fn as_str(self) -> &'static str {
        match self {
            ClaimAttemptStatus::Pending => "pending",
            ClaimAttemptStatus::Completed => "completed",
            ClaimAttemptStatus::Expired => "expired",
        }
    }

    fn from_string(value: String) -> Self {
        match value.as_str() {
            "pending" => ClaimAttemptStatus::Pending,
            "completed" => ClaimAttemptStatus::Completed,
            "expired" => ClaimAttemptStatus::Expired,
            _ => ClaimAttemptStatus::Expired,
        }
    }
}

/// Full agent identity row. Scope fields are stored as JSON array strings; route code owns
/// parsing/validation because it knows the applicable grant flow and permission grammar.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct AgentIdentityRow {
    pub(crate) id: String,
    /// The owning account DID, or `None` for an unclaimed `anonymous` registration (V038): an
    /// anonymous identity has no owning account until a later claim ceremony binds one.
    pub(crate) did: Option<String>,
    pub(crate) registration_type: RegistrationType,
    pub(crate) issuer: Option<String>,
    pub(crate) subject: Option<String>,
    pub(crate) email: Option<String>,
    pub(crate) scopes: String,
    pub(crate) identity_assertion: Option<String>,
    pub(crate) assertion_expires_at: String,
    pub(crate) pre_claim_scopes: Option<String>,
    pub(crate) claim_token: Option<String>,
    pub(crate) claim_token_expires_at: Option<String>,
    pub(crate) status: AgentIdentityStatus,
    pub(crate) created_at: String,
    pub(crate) updated_at: String,
}

/// Fields needed to insert an agent identity. IDs/tokens/assertions are generated by callers.
pub(crate) struct NewAgentIdentity<'a> {
    pub(crate) id: &'a str,
    /// The owning account DID, or `None` for an unclaimed `anonymous` registration (V038).
    pub(crate) did: Option<&'a str>,
    pub(crate) registration_type: RegistrationType,
    pub(crate) issuer: Option<&'a str>,
    pub(crate) subject: Option<&'a str>,
    pub(crate) email: Option<&'a str>,
    pub(crate) scopes: &'a str,
    pub(crate) identity_assertion: Option<&'a str>,
    pub(crate) assertion_expires_at: &'a str,
    pub(crate) pre_claim_scopes: Option<&'a str>,
    pub(crate) claim_token: Option<&'a str>,
    pub(crate) claim_token_expires_at: Option<&'a str>,
}

/// Result of inserting an agent identity.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum InsertAgentIdentityOutcome {
    Created,
    /// Primary-key or `(issuer, subject)` uniqueness collision.
    Duplicate,
}

/// Claim ceremony row with expiry derived at query time.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct AgentClaimAttemptRow {
    pub(crate) id: String,
    pub(crate) identity_id: String,
    pub(crate) user_code: String,
    pub(crate) user_code_expires_at: String,
    pub(crate) email: Option<String>,
    pub(crate) status: ClaimAttemptStatus,
    pub(crate) created_at: String,
    /// Derived: `datetime(user_code_expires_at) <= datetime('now')` at query time.
    pub(crate) is_expired: bool,
}

impl AgentClaimAttemptRow {
    /// A claim attempt can be completed only while pending and unexpired.
    pub(crate) fn is_pending(&self) -> bool {
        self.status == ClaimAttemptStatus::Pending && !self.is_expired
    }
}

/// Fields needed to insert a user-code claim attempt.
pub(crate) struct NewAgentClaimAttempt<'a> {
    pub(crate) id: &'a str,
    pub(crate) identity_id: &'a str,
    pub(crate) user_code: &'a str,
    pub(crate) user_code_expires_at: &'a str,
    pub(crate) email: Option<&'a str>,
}

/// Insert a new agent identity row. Generic over the executor so future route code can
/// compose registration and claim-attempt writes inside one transaction.
pub(crate) async fn insert_agent_identity<'e, E>(
    executor: E,
    identity: &NewAgentIdentity<'_>,
) -> Result<InsertAgentIdentityOutcome, ApiError>
where
    E: sqlx::Executor<'e, Database = Sqlite>,
{
    let result = sqlx::query(
        "INSERT INTO agent_identities \
         (id, did, registration_type, issuer, subject, email, scopes, identity_assertion, \
          assertion_expires_at, pre_claim_scopes, claim_token, claim_token_expires_at, \
          created_at, updated_at) \
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, datetime('now'), datetime('now'))",
    )
    .bind(identity.id)
    .bind(identity.did)
    .bind(identity.registration_type.as_str())
    .bind(identity.issuer)
    .bind(identity.subject)
    .bind(identity.email)
    .bind(identity.scopes)
    .bind(identity.identity_assertion)
    .bind(identity.assertion_expires_at)
    .bind(identity.pre_claim_scopes)
    .bind(identity.claim_token)
    .bind(identity.claim_token_expires_at)
    .execute(executor)
    .await;

    match result {
        Ok(_) => Ok(InsertAgentIdentityOutcome::Created),
        Err(e) if is_unique_violation(&e) => Ok(InsertAgentIdentityOutcome::Duplicate),
        Err(e) => {
            tracing::error!(identity_id = %identity.id, error = %e, "DB error inserting agent identity");
            Err(ApiError::new(
                ErrorCode::InternalError,
                "failed to create agent identity",
            ))
        }
    }
}

/// Fetch an agent identity by registration id.
pub(crate) async fn get_agent_identity(
    db: &sqlx::SqlitePool,
    id: &str,
) -> Result<Option<AgentIdentityRow>, ApiError> {
    fetch_identity_by(db, "id", id).await
}

/// Fetch an agent identity by one-time claim token.
pub(crate) async fn get_agent_identity_by_claim_token(
    db: &sqlx::SqlitePool,
    claim_token: &str,
) -> Result<Option<AgentIdentityRow>, ApiError> {
    fetch_identity_by(db, "claim_token", claim_token).await
}

/// Fetch an agent identity by its `(issuer, subject)` pair.
///
/// Backs the `identity_assertion` flow: an ID-JAG's `(iss, sub)` is the stable key for an agent's
/// registration, deduplicated by the partial unique index `idx_agent_identities_iss_sub`.
pub(crate) async fn get_agent_identity_by_issuer_subject(
    db: &sqlx::SqlitePool,
    issuer: &str,
    subject: &str,
) -> Result<Option<AgentIdentityRow>, ApiError> {
    let row = sqlx::query_as::<_, IdentitySqlRow>(
        "SELECT id, did, registration_type, issuer, subject, email, scopes, identity_assertion, \
                assertion_expires_at, pre_claim_scopes, claim_token, claim_token_expires_at, \
                status, created_at, updated_at \
         FROM agent_identities WHERE issuer = ? AND subject = ?",
    )
    .bind(issuer)
    .bind(subject)
    .fetch_optional(db)
    .await
    .map_err(|e| {
        tracing::error!(error = %e, "DB error fetching agent identity by issuer/subject");
        ApiError::new(ErrorCode::InternalError, "failed to load agent identity")
    })?;
    Ok(row.map(into_identity_row))
}

async fn fetch_identity_by(
    db: &sqlx::SqlitePool,
    column: &str,
    value: &str,
) -> Result<Option<AgentIdentityRow>, ApiError> {
    let sql = match column {
        "id" => {
            "SELECT id, did, registration_type, issuer, subject, email, scopes, identity_assertion, \
                    assertion_expires_at, pre_claim_scopes, claim_token, claim_token_expires_at, \
                    status, created_at, updated_at \
             FROM agent_identities WHERE id = ?"
        }
        "claim_token" => {
            "SELECT id, did, registration_type, issuer, subject, email, scopes, identity_assertion, \
                    assertion_expires_at, pre_claim_scopes, claim_token, claim_token_expires_at, \
                    status, created_at, updated_at \
             FROM agent_identities WHERE claim_token = ?"
        }
        _ => unreachable!("unsupported agent identity lookup column"),
    };

    let row = sqlx::query_as::<_, IdentitySqlRow>(sql)
    .bind(value)
    .fetch_optional(db)
    .await
    .map_err(|e| {
        tracing::error!(lookup_column = %column, error = %e, "DB error fetching agent identity");
        ApiError::new(ErrorCode::InternalError, "failed to load agent identity")
    })?;

    Ok(row.map(into_identity_row))
}

/// Update identity status. Used by claim completion and revocation flows.
pub(crate) async fn set_agent_identity_status<'e, E>(
    executor: E,
    id: &str,
    status: AgentIdentityStatus,
) -> Result<bool, ApiError>
where
    E: sqlx::Executor<'e, Database = Sqlite>,
{
    let result = sqlx::query(
        "UPDATE agent_identities SET status = ?, updated_at = datetime('now') WHERE id = ?",
    )
    .bind(status.as_str())
    .bind(id)
    .execute(executor)
    .await
    .map_err(|e| {
        tracing::error!(identity_id = %id, error = %e, "DB error updating agent identity status");
        ApiError::new(ErrorCode::InternalError, "failed to update agent identity")
    })?;
    Ok(result.rows_affected() == 1)
}

/// Store a freshly minted service assertion for an identity.
pub(crate) async fn set_agent_identity_assertion<'e, E>(
    executor: E,
    id: &str,
    identity_assertion: &str,
    assertion_expires_at: &str,
) -> Result<bool, ApiError>
where
    E: sqlx::Executor<'e, Database = Sqlite>,
{
    let result = sqlx::query(
        "UPDATE agent_identities \
         SET identity_assertion = ?, assertion_expires_at = ?, updated_at = datetime('now') \
         WHERE id = ?",
    )
    .bind(identity_assertion)
    .bind(assertion_expires_at)
    .bind(id)
    .execute(executor)
    .await
    .map_err(|e| {
        tracing::error!(identity_id = %id, error = %e, "DB error updating agent identity assertion");
        ApiError::new(ErrorCode::InternalError, "failed to update agent identity")
    })?;
    Ok(result.rows_affected() == 1)
}

/// Atomically claim an `active` agent identity: bind an owning DID (for a previously ownerless
/// `anonymous` registration), store the freshly minted post-claim assertion and its granted scopes,
/// and flip the status to `claimed` — all in one single-table UPDATE.
///
/// `bind_did` is `Some(did)` only for the `anonymous` flow (whose `did` was NULL); pass `None` for a
/// registration already bound at registration time (`service_auth` / `identity_assertion`), where
/// `COALESCE(NULL, did)` leaves the existing owner untouched. The `status = 'active'` guard makes the
/// claim idempotent-safe: a concurrent or repeat confirmation of an already-`claimed`/`revoked`
/// identity affects no rows and returns `false`.
pub(crate) async fn claim_agent_identity<'e, E>(
    executor: E,
    id: &str,
    bind_did: Option<&str>,
    scopes: &str,
    identity_assertion: &str,
    assertion_expires_at: &str,
) -> Result<bool, ApiError>
where
    E: sqlx::Executor<'e, Database = Sqlite>,
{
    let result = sqlx::query(
        "UPDATE agent_identities \
         SET status = 'claimed', \
             did = COALESCE(?, did), \
             scopes = ?, \
             identity_assertion = ?, \
             assertion_expires_at = ?, \
             updated_at = datetime('now') \
         WHERE id = ? AND status = 'active'",
    )
    .bind(bind_did)
    .bind(scopes)
    .bind(identity_assertion)
    .bind(assertion_expires_at)
    .bind(id)
    .execute(executor)
    .await
    .map_err(|e| {
        tracing::error!(identity_id = %id, error = %e, "DB error claiming agent identity");
        ApiError::new(ErrorCode::InternalError, "failed to claim agent identity")
    })?;
    Ok(result.rows_affected() == 1)
}

/// Insert a new claim ceremony attempt.
pub(crate) async fn insert_agent_claim_attempt<'e, E>(
    executor: E,
    attempt: &NewAgentClaimAttempt<'_>,
) -> Result<(), ApiError>
where
    E: sqlx::Executor<'e, Database = Sqlite>,
{
    sqlx::query(
        "INSERT INTO agent_claim_attempts \
         (id, identity_id, user_code, user_code_expires_at, email, created_at) \
         VALUES (?, ?, ?, ?, ?, datetime('now'))",
    )
    .bind(attempt.id)
    .bind(attempt.identity_id)
    .bind(attempt.user_code)
    .bind(attempt.user_code_expires_at)
    .bind(attempt.email)
    .execute(executor)
    .await
    .map_err(|e| {
        tracing::error!(attempt_id = %attempt.id, identity_id = %attempt.identity_id, error = %e, "DB error inserting agent claim attempt");
        ApiError::new(
            ErrorCode::InternalError,
            "failed to create agent claim attempt",
        )
    })?;
    Ok(())
}

/// Fetch a claim attempt by its user-facing code.
pub(crate) async fn get_agent_claim_attempt_by_user_code(
    db: &sqlx::SqlitePool,
    user_code: &str,
) -> Result<Option<AgentClaimAttemptRow>, ApiError> {
    let row = sqlx::query_as::<_, ClaimAttemptSqlRow>(
        "SELECT id, identity_id, user_code, user_code_expires_at, email, status, created_at, \
                datetime(user_code_expires_at) <= datetime('now') AS is_expired \
         FROM agent_claim_attempts \
         WHERE user_code = ?",
    )
    .bind(user_code)
    .fetch_optional(db)
    .await
    .map_err(|e| {
        tracing::error!(error = %e, "DB error fetching agent claim attempt by user code");
        ApiError::new(ErrorCode::InternalError, "failed to load claim attempt")
    })?;
    Ok(row.map(into_claim_attempt_row))
}

/// Fetch the newest claim attempt for an identity.
pub(crate) async fn latest_agent_claim_attempt_for_identity(
    db: &sqlx::SqlitePool,
    identity_id: &str,
) -> Result<Option<AgentClaimAttemptRow>, ApiError> {
    let row = sqlx::query_as::<_, ClaimAttemptSqlRow>(
        "SELECT id, identity_id, user_code, user_code_expires_at, email, status, created_at, \
                datetime(user_code_expires_at) <= datetime('now') AS is_expired \
         FROM agent_claim_attempts \
         WHERE identity_id = ? ORDER BY created_at DESC, id DESC LIMIT 1",
    )
    .bind(identity_id)
    .fetch_optional(db)
    .await
    .map_err(|e| {
        tracing::error!(identity_id = %identity_id, error = %e, "DB error fetching latest agent claim attempt");
        ApiError::new(ErrorCode::InternalError, "failed to load claim attempt")
    })?;
    Ok(row.map(into_claim_attempt_row))
}

/// Atomically complete a pending, unexpired claim attempt.
pub(crate) async fn complete_agent_claim_attempt<'e, E>(
    executor: E,
    id: &str,
) -> Result<bool, ApiError>
where
    E: sqlx::Executor<'e, Database = Sqlite>,
{
    let result = sqlx::query(
        "UPDATE agent_claim_attempts SET status = 'completed' \
         WHERE id = ? AND status = 'pending' AND datetime(user_code_expires_at) > datetime('now')",
    )
    .bind(id)
    .execute(executor)
    .await
    .map_err(|e| {
        tracing::error!(attempt_id = %id, error = %e, "DB error completing agent claim attempt");
        ApiError::new(ErrorCode::InternalError, "failed to complete claim attempt")
    })?;
    Ok(result.rows_affected() == 1)
}

/// Mark any expired pending attempts as expired. Returns the number of affected rows.
pub(crate) async fn expire_pending_agent_claim_attempts<'e, E>(executor: E) -> Result<u64, ApiError>
where
    E: sqlx::Executor<'e, Database = Sqlite>,
{
    let result = sqlx::query(
        "UPDATE agent_claim_attempts SET status = 'expired' \
         WHERE status = 'pending' AND datetime(user_code_expires_at) <= datetime('now')",
    )
    .execute(executor)
    .await
    .map_err(|e| {
        tracing::error!(error = %e, "DB error expiring agent claim attempts");
        ApiError::new(ErrorCode::InternalError, "failed to expire claim attempts")
    })?;
    Ok(result.rows_affected())
}

fn into_identity_row(row: IdentitySqlRow) -> AgentIdentityRow {
    let (
        id,
        did,
        registration_type,
        issuer,
        subject,
        email,
        scopes,
        identity_assertion,
        assertion_expires_at,
        pre_claim_scopes,
        claim_token,
        claim_token_expires_at,
        status,
        created_at,
        updated_at,
    ) = row;

    AgentIdentityRow {
        id,
        did,
        registration_type: RegistrationType::from_string(registration_type),
        issuer,
        subject,
        email,
        scopes,
        identity_assertion,
        assertion_expires_at,
        pre_claim_scopes,
        claim_token,
        claim_token_expires_at,
        status: AgentIdentityStatus::from_string(status),
        created_at,
        updated_at,
    }
}

fn into_claim_attempt_row(row: ClaimAttemptSqlRow) -> AgentClaimAttemptRow {
    let (id, identity_id, user_code, user_code_expires_at, email, status, created_at, is_expired) =
        row;
    AgentClaimAttemptRow {
        id,
        identity_id,
        user_code,
        user_code_expires_at,
        email,
        status: ClaimAttemptStatus::from_string(status),
        created_at,
        is_expired,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::db::{open_pool, run_migrations};

    async fn test_pool() -> sqlx::SqlitePool {
        let pool = open_pool("sqlite::memory:").await.unwrap();
        run_migrations(&pool).await.unwrap();
        pool
    }

    async fn insert_account(pool: &sqlx::SqlitePool, did: &str) {
        sqlx::query(
            "INSERT INTO accounts (did, email, password_hash, created_at, updated_at) \
             VALUES (?, ?, 'hash', datetime('now'), datetime('now'))",
        )
        .bind(did)
        .bind(format!("{}@example.com", did.replace(':', "-")))
        .execute(pool)
        .await
        .unwrap();
    }

    fn new_identity<'a>(id: &'a str, did: &'a str) -> NewAgentIdentity<'a> {
        NewAgentIdentity {
            id,
            did: Some(did),
            registration_type: RegistrationType::Anonymous,
            issuer: None,
            subject: None,
            email: None,
            scopes: r#"["com.atproto.access"]"#,
            identity_assertion: Some("assertion.jwt"),
            assertion_expires_at: "2099-01-01T00:00:00Z",
            pre_claim_scopes: Some(r#"["com.atproto.access"]"#),
            claim_token: Some("clm_test"),
            claim_token_expires_at: Some("2099-01-01T00:00:00Z"),
        }
    }

    #[tokio::test]
    async fn insert_and_fetch_identity_by_id_and_claim_token() {
        let pool = test_pool().await;
        let did = "did:plc:agentauthowner1111111111";
        insert_account(&pool, did).await;

        let outcome = insert_agent_identity(&pool, &new_identity("reg_1", did))
            .await
            .unwrap();
        assert_eq!(outcome, InsertAgentIdentityOutcome::Created);

        let by_id = get_agent_identity(&pool, "reg_1").await.unwrap().unwrap();
        assert_eq!(by_id.id, "reg_1");
        assert_eq!(by_id.did.as_deref(), Some(did));
        assert_eq!(by_id.registration_type, RegistrationType::Anonymous);
        assert_eq!(by_id.status, AgentIdentityStatus::Active);
        assert_eq!(by_id.claim_token.as_deref(), Some("clm_test"));

        let by_claim = get_agent_identity_by_claim_token(&pool, "clm_test")
            .await
            .unwrap()
            .unwrap();
        assert_eq!(by_claim.id, "reg_1");
    }

    #[tokio::test]
    async fn anonymous_identity_persists_without_owning_did() {
        // V038 made `did` nullable so an anonymous registration (no owning account yet) can be
        // stored. Insert one with `did: None` and read it back.
        let pool = test_pool().await;
        let anon = NewAgentIdentity {
            did: None,
            issuer: None,
            subject: None,
            ..new_identity("reg_anon", "unused")
        };
        assert_eq!(
            insert_agent_identity(&pool, &anon).await.unwrap(),
            InsertAgentIdentityOutcome::Created
        );

        let row = get_agent_identity(&pool, "reg_anon")
            .await
            .unwrap()
            .unwrap();
        assert_eq!(row.did, None);
        assert_eq!(row.status, AgentIdentityStatus::Active);
        assert_eq!(row.claim_token.as_deref(), Some("clm_test"));
    }

    #[tokio::test]
    async fn duplicate_issuer_subject_reported_as_duplicate() {
        let pool = test_pool().await;
        let did = "did:plc:agentauthowner2222222222";
        insert_account(&pool, did).await;

        let first = NewAgentIdentity {
            id: "reg_issuer_1",
            registration_type: RegistrationType::IdentityAssertion,
            issuer: Some("https://issuer.example.com"),
            subject: Some("subject-1"),
            ..new_identity("reg_issuer_1", did)
        };
        let second = NewAgentIdentity {
            id: "reg_issuer_2",
            registration_type: RegistrationType::IdentityAssertion,
            issuer: Some("https://issuer.example.com"),
            subject: Some("subject-1"),
            claim_token: Some("clm_other"),
            ..new_identity("reg_issuer_2", did)
        };

        assert_eq!(
            insert_agent_identity(&pool, &first).await.unwrap(),
            InsertAgentIdentityOutcome::Created
        );
        assert_eq!(
            insert_agent_identity(&pool, &second).await.unwrap(),
            InsertAgentIdentityOutcome::Duplicate
        );
    }

    #[tokio::test]
    async fn identity_status_and_assertion_can_be_updated() {
        let pool = test_pool().await;
        let did = "did:plc:agentauthowner3333333333";
        insert_account(&pool, did).await;
        insert_agent_identity(&pool, &new_identity("reg_update", did))
            .await
            .unwrap();

        assert!(
            set_agent_identity_status(&pool, "reg_update", AgentIdentityStatus::Claimed)
                .await
                .unwrap()
        );
        assert!(set_agent_identity_assertion(
            &pool,
            "reg_update",
            "new.assertion.jwt",
            "2099-02-01T00:00:00Z",
        )
        .await
        .unwrap());

        let row = get_agent_identity(&pool, "reg_update")
            .await
            .unwrap()
            .unwrap();
        assert_eq!(row.status, AgentIdentityStatus::Claimed);
        assert_eq!(row.identity_assertion.as_deref(), Some("new.assertion.jwt"));
        assert_eq!(row.assertion_expires_at, "2099-02-01T00:00:00Z");
    }

    #[tokio::test]
    async fn claim_attempt_lifecycle_is_atomic_and_expiry_aware() {
        let pool = test_pool().await;
        let did = "did:plc:agentauthowner4444444444";
        insert_account(&pool, did).await;
        insert_agent_identity(&pool, &new_identity("reg_claim", did))
            .await
            .unwrap();

        insert_agent_claim_attempt(
            &pool,
            &NewAgentClaimAttempt {
                id: "cla_pending",
                identity_id: "reg_claim",
                user_code: "123456",
                user_code_expires_at: "2099-01-01T00:00:00Z",
                email: Some("user@example.com"),
            },
        )
        .await
        .unwrap();

        let attempt = get_agent_claim_attempt_by_user_code(&pool, "123456")
            .await
            .unwrap()
            .unwrap();
        assert_eq!(attempt.id, "cla_pending");
        assert!(attempt.is_pending());

        assert!(complete_agent_claim_attempt(&pool, "cla_pending")
            .await
            .unwrap());
        assert!(!complete_agent_claim_attempt(&pool, "cla_pending")
            .await
            .unwrap());

        let latest = latest_agent_claim_attempt_for_identity(&pool, "reg_claim")
            .await
            .unwrap()
            .unwrap();
        assert_eq!(latest.status, ClaimAttemptStatus::Completed);
        assert!(!latest.is_pending());
    }

    #[tokio::test]
    async fn expired_attempts_are_marked_and_cannot_complete() {
        let pool = test_pool().await;
        let did = "did:plc:agentauthowner5555555555";
        insert_account(&pool, did).await;
        insert_agent_identity(&pool, &new_identity("reg_expired", did))
            .await
            .unwrap();
        insert_agent_claim_attempt(
            &pool,
            &NewAgentClaimAttempt {
                id: "cla_expired",
                identity_id: "reg_expired",
                user_code: "654321",
                user_code_expires_at: "2000-01-01T00:00:00Z",
                email: None,
            },
        )
        .await
        .unwrap();

        assert!(!complete_agent_claim_attempt(&pool, "cla_expired")
            .await
            .unwrap());
        assert_eq!(expire_pending_agent_claim_attempts(&pool).await.unwrap(), 1);

        let attempt = get_agent_claim_attempt_by_user_code(&pool, "654321")
            .await
            .unwrap()
            .unwrap();
        assert_eq!(attempt.status, ClaimAttemptStatus::Expired);
        assert!(attempt.is_expired);
    }

    #[tokio::test]
    async fn claim_binds_owner_upgrades_assertion_and_flips_status() {
        let pool = test_pool().await;
        let did = "did:plc:agentauthclaim1111111";
        insert_account(&pool, did).await;

        // An ownerless (anonymous) registration: did NULL, active, narrow pre-claim scopes.
        let anon = NewAgentIdentity {
            did: None,
            scopes: r#"["blob:*/*"]"#,
            pre_claim_scopes: Some(r#"["blob:*/*"]"#),
            identity_assertion: Some("pre.claim.jwt"),
            ..new_identity("reg_claimbind", "unused")
        };
        insert_agent_identity(&pool, &anon).await.unwrap();

        // The claim binds the owner, upgrades scopes + assertion, and flips to claimed.
        assert!(claim_agent_identity(
            &pool,
            "reg_claimbind",
            Some(did),
            r#"["atproto","repo:*?action=create&action=update","blob:*/*"]"#,
            "post.claim.jwt",
            "2099-03-01T00:00:00Z",
        )
        .await
        .unwrap());

        let row = get_agent_identity(&pool, "reg_claimbind")
            .await
            .unwrap()
            .unwrap();
        assert_eq!(row.did.as_deref(), Some(did));
        assert_eq!(row.status, AgentIdentityStatus::Claimed);
        assert_eq!(row.identity_assertion.as_deref(), Some("post.claim.jwt"));
        assert_eq!(
            row.scopes,
            r#"["atproto","repo:*?action=create&action=update","blob:*/*"]"#
        );

        // Re-claiming an already-claimed identity is a no-op (status guard) → affects no rows.
        assert!(!claim_agent_identity(
            &pool,
            "reg_claimbind",
            Some(did),
            r#"["atproto"]"#,
            "other.jwt",
            "2099-04-01T00:00:00Z",
        )
        .await
        .unwrap());
    }

    #[tokio::test]
    async fn claim_with_no_bind_did_preserves_prebound_owner() {
        let pool = test_pool().await;
        let did = "did:plc:agentauthclaim2222222";
        insert_account(&pool, did).await;

        // A service_auth-style registration already bound to an owner at registration time.
        insert_agent_identity(&pool, &new_identity("reg_prebound", did))
            .await
            .unwrap();

        // Claiming with no bind_did: COALESCE(NULL, did) keeps the existing owner.
        assert!(claim_agent_identity(
            &pool,
            "reg_prebound",
            None,
            r#"["atproto"]"#,
            "bound.jwt",
            "2099-05-01T00:00:00Z",
        )
        .await
        .unwrap());

        let row = get_agent_identity(&pool, "reg_prebound")
            .await
            .unwrap()
            .unwrap();
        assert_eq!(row.did.as_deref(), Some(did));
        assert_eq!(row.status, AgentIdentityStatus::Claimed);
    }
}
