// Test harness: spawns a hermetic local PDS and provisions a real account
// through the same ceremony the identity wallet uses, reusing the plumbing
// from tools/interop. plc.directory is mocked so no test traffic ever reaches
// the live network.
//
// The PDS requires an https public_url (RFC 8414), so each spawned instance
// is fronted by a loopback TLS proxy using the throwaway cert generated by
// test/run.ts; everything a client discovers (issuer, endpoints, resource)
// is the https proxy origin.

import { spawn, type ChildProcess } from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  pdsBinary as locatePdsBinary,
  freePort,
  startMockPlc,
  startTlsProxy,
} from 'ezpds-interop/src/hermetic-pds.js';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..', '..');

export const ADMIN_TOKEN = 'mcp-conformance-admin-token';

function pdsBinary(): string {
  return locatePdsBinary(repoRoot, process.env.CUSTOS_MCP_TEST_PDS_BIN);
}

function tlsMaterial(): { key: Buffer; cert: Buffer } {
  const dir = process.env.CUSTOS_MCP_TEST_TLS_DIR;
  if (!dir) {
    throw new Error('CUSTOS_MCP_TEST_TLS_DIR is not set — run the suite via `pnpm test`');
  }
  return {
    key: fs.readFileSync(path.join(dir, 'key.pem')),
    cert: fs.readFileSync(path.join(dir, 'cert.pem')),
  };
}

export { startMockPlc };

export interface SpawnedPds {
  /** The https origin clients use — also the PDS's configured public_url. */
  baseUrl: string;
  proc: ChildProcess;
  dataDir: string;
  stop: () => void;
}

/**
 * Spawn the pds binary configured entirely from env vars (cwd points at an
 * empty dir so no pds.toml is picked up), fronted by a TLS proxy, and wait
 * for /xrpc/_health.
 */
export async function spawnPds(options: {
  dir: string;
  plcUrl: string;
  agentAuthEnabled: boolean;
  /** Override [agent_auth] granted_scopes (comma-joined into the env var). */
  grantedScopes?: string[];
}): Promise<SpawnedPds> {
  const proxy = await startTlsProxy(tlsMaterial());
  const httpPort = await freePort();
  proxy.setUpstreamPort(httpPort);
  const baseUrl = `https://127.0.0.1:${proxy.port}`;
  const dataDir = path.join(options.dir, 'data');
  fs.mkdirSync(dataDir, { recursive: true });

  const proc = spawn(pdsBinary(), [], {
    cwd: options.dir,
    env: {
      PATH: process.env.PATH ?? '',
      EZPDS_DATA_DIR: dataDir,
      EZPDS_DATABASE_URL: path.join(dataDir, 'pds.db'),
      EZPDS_BIND_ADDRESS: '127.0.0.1',
      EZPDS_PORT: String(httpPort),
      EZPDS_PUBLIC_URL: baseUrl,
      EZPDS_AVAILABLE_USER_DOMAINS: 'localhost',
      EZPDS_ADMIN_TOKEN: ADMIN_TOKEN,
      EZPDS_PLC_DIRECTORY_URL: options.plcUrl,
      // Throwaway: encrypts per-account repo signing keys in the test DB.
      EZPDS_SIGNING_KEY_MASTER_KEY: '00'.repeat(32),
      // The spaces surface is off by default (pre-launch alpha); the space tools'
      // conformance tests need it served.
      EZPDS_SPACES_ENABLED: 'true',
      EZPDS_RATE_LIMIT_ENABLED: 'false',
      EZPDS_AGENT_AUTH_SERVICE_AUTH_ENABLED: options.agentAuthEnabled ? 'true' : 'false',
      // The MCP server itself only uses service_auth; anonymous is on so the suite can also
      // drive the cooperative child-mint arm of the claim ceremony, which starts there.
      EZPDS_AGENT_AUTH_ANONYMOUS_ENABLED: options.agentAuthEnabled ? 'true' : 'false',
      ...(options.grantedScopes
        ? { EZPDS_AGENT_AUTH_GRANTED_SCOPES: options.grantedScopes.join(',') }
        : {}),
    },
    stdio: ['ignore', 'pipe', 'pipe'],
  });
  const logs: string[] = [];
  proc.stdout!.on('data', (chunk) => logs.push(String(chunk)));
  proc.stderr!.on('data', (chunk) => logs.push(String(chunk)));

  const deadline = Date.now() + 30_000;
  for (;;) {
    if (proc.exitCode !== null) {
      proxy.close();
      throw new Error(`pds exited with ${proc.exitCode} during startup:\n${logs.join('')}`);
    }
    try {
      const res = await fetch(`http://127.0.0.1:${httpPort}/xrpc/_health`, {
        signal: AbortSignal.timeout(2_000),
      });
      if (res.ok) break;
    } catch {
      // not up yet
    }
    if (Date.now() > deadline) {
      proc.kill();
      proxy.close();
      throw new Error(`pds did not become healthy within 30s:\n${logs.join('')}`);
    }
    await new Promise((r) => setTimeout(r, 200));
  }

  return {
    baseUrl,
    proc,
    dataDir,
    stop: () => {
      proc.kill();
      proxy.close();
    },
  };
}

export interface TestAccount {
  did: string;
  handle: string;
  email: string;
  accessJwt: string;
}

/**
 * Provision a full account (claim code → mobile account → repo signing key →
 * client-signed did:plc genesis → handle → session) by reusing
 * tools/interop's account ceremony against the spawned PDS.
 */
export async function provisionAccount(baseUrl: string, stateDir: string): Promise<TestAccount> {
  // interop's config module reads these at first import, so they must be set
  // before the dynamic import below.
  process.env.EZPDS_BASE_URL = baseUrl;
  process.env.EZPDS_ADMIN_TOKEN = ADMIN_TOKEN;
  process.env.EZPDS_INTEROP_STATE_DIR = stateDir;
  process.env.EZPDS_INTEROP_PACE_MS = '25';

  const account = await import('ezpds-interop/src/account.js');
  const created = await account.createAccount({ name: 'mcp-conformance', kind: 'ephemeral' });
  return {
    did: created.did,
    handle: created.handle,
    email: created.email,
    accessJwt: created.accessJwt,
  };
}

/** The human half of the ceremony: confirm the claim code as the account owner. */
export async function confirmClaim(
  baseUrl: string,
  ownerAccessJwt: string,
  userCode: string,
): Promise<void> {
  const res = await fetch(`${baseUrl}/agent/identity/claim/confirm`, {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      authorization: `Bearer ${ownerAccessJwt}`,
    },
    body: JSON.stringify({ user_code: userCode }),
  });
  const body = (await res.json()) as { status?: string };
  if (!res.ok) {
    throw new Error(`claim confirm failed (${res.status}): ${JSON.stringify(body)}`);
  }
  if (body.status !== 'claimed') {
    throw new Error(`unexpected claim confirm status: ${JSON.stringify(body)}`);
  }
}
