pub mod account_storage;
pub mod account_usage;
pub mod activate_account;
pub mod admin_devices;
pub mod admin_health;
pub mod admin_list_accounts;
pub mod admin_revoke_credentials;
mod admin_subject_defs;
pub mod admin_transfers;
pub mod agent_claim;
pub mod agent_event;
pub mod agent_identity;
pub mod agents;
pub mod apply_writes;
pub mod atproto_did;
pub mod auth_md;
pub mod check_account_status;
pub mod claim_codes;
pub mod confirm_email;
pub mod create_account;
pub mod create_account_xrpc;
pub mod create_app_password;
pub mod create_did;
pub mod create_handle;
pub mod create_mobile_account;
pub mod create_record;
pub mod create_session;
pub mod create_signing_key;
pub mod deactivate_account;
pub mod delete_account;
pub mod delete_handle;
pub mod delete_record;
pub mod delete_session;
pub mod describe_repo;
pub mod describe_server;
pub mod get_blob;
pub mod get_device_pds;
pub mod get_did;
pub mod get_metrics;
pub mod get_pds_signing_key;
pub mod get_preferences;
pub mod get_recommended_did_credentials;
pub mod get_record;
pub mod get_repo;
pub mod get_repo_signing_key;
pub mod get_service_auth;
pub mod get_session;
pub mod get_subject_status;
pub mod health;
pub mod import_repo;
pub mod landing;
pub mod list_app_passwords;
pub mod list_blobs;
pub mod list_missing_blobs;
pub mod list_records;
pub mod list_repos;
pub mod oauth_authorize;
pub mod oauth_client_metadata;
pub(super) mod oauth_errors;
pub mod oauth_jwks;
pub mod oauth_par;
pub mod oauth_protected_resource;
pub mod oauth_revoke;
pub mod oauth_server_metadata;
pub(super) mod oauth_templates;
pub mod oauth_token;
pub mod provisioning_session;
pub mod put_preferences;
pub mod put_record;
pub mod refresh_session;
pub mod register_device;
pub mod request_account_delete;
pub mod request_email_confirmation;
pub mod request_email_update;
pub mod request_password_reset;
pub mod request_plc_operation_signature;
pub mod reserve_signing_key;
pub mod reset_password;
pub mod resolve_handle;
pub mod resolve_identity;
pub mod revoke_app_password;
pub mod service_proxy;
pub mod sign_plc_operation;
pub mod sovereign_session;
pub mod standard_signup;
pub mod static_assets;
pub mod submit_plc_operation;
pub mod sync_get_blocks;
pub mod sync_get_latest_commit;
pub mod sync_get_record;
pub mod sync_get_repo_status;
pub mod sync_subscribe_repos;
pub mod transfer_accept;
pub mod transfer_complete;
pub mod transfer_initiate;
pub mod update_email;
pub mod update_handle;
pub mod update_subject_status;
pub mod upload_blob;

mod preference_scope;

#[cfg(test)]
pub(crate) mod test_utils;

#[cfg(test)]
mod outbound_migration_test;

#[cfg(test)]
mod agent_auth_test;
